[package]
name = "ruscall-online"
version = "0.1.0"
authors = ["elipmoc <relipmoc101@gmail.com>"]

[dependencies]
ruscall={git="https://github.com/elipmoc/Ruscall.git", branch="develop"}
actix-web = "0.7"
serde_derive = "1.0.80"
serde="1"
serde_json="1"